name: Codex Task (Task Assistant)
description: Create a deterministic, machine-executable task for Codex
title: "[Codex] <short task summary>"
labels:
  - codex:execute
  - phase-3
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Codex Task Issue

        This issue is intended to be executed by **Codex**.

        ⚠️ **Important**
        - Codex will only run if a valid ` ```codex ` intent block is present
        - Invalid or missing intent blocks result in **BLOCKED**
        - See: `docs/codex/intent-spec.md`

  - type: textarea
    id: intent
    attributes:
      label: Codex Intent Block (Required)
      description: |
        This block is parsed verbatim by Codex.
        - Do not change the structure
        - Use valid JSON only
        - Exactly one block is allowed
      render: markdown
      value: |
        ```codex
        {
          "version": "1.1",
          "task": "<task-id>",
          "instructions": [
            "<imperative instruction>",
            "<imperative instruction>"
          ],
          "constraints": [
            "<optional constraint>"
          ],
          "validation": {
            "commands": [
              "<optional validation command>"
            ],
            "notes": [
              "<optional human-readable note>"
            ]
          }
        }
        ```
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (Optional)
      description: |
        Human-readable context for reviewers.
        This section is ignored by Codex.
      placeholder: |
        Background, rationale, or links relevant to this task.

  - type: checkboxes
    id: safety
    attributes:
      label: Safety & Scope Confirmation
      options:
        - label: I confirm this issue contains exactly one valid ` ```codex ` intent block
          required: true
        - label: I confirm the task is safe to execute automatically
          required: true
        - label: I understand Codex may open a pull request
          required: true
